version: "3.9"

services:
  backend:
    build: ./ProjetBI-Back
    container_name: eventzella-backend
    restart: always
    ports:
      - "8000:5000"
      - "5000:5000"
    env_file:
      - ./ProjetBI-Back/.env
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - eventzella-network

  frontend:
    build: ./ProjetBi-Front
    container_name: eventzella-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eventzella-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventzella-sqlserver
    restart: always
    environment:
      SA_PASSWORD: "EventZella2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'Recovery is complete' /var/opt/mssql/log/errorlog || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    networks:
      - eventzella-network
    volumes:
      - sql_data:/var/opt/mssql

networks:
  eventzella-network:
    driver: bridge

volumes:
  sql_data: